spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:file:./duskio;TRACE_LEVEL_FILE=0;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;NON_KEYWORDS=VALUE;AUTO_SERVER=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${duskio.keycloak-endpoint}/realms/${duskio.keycloak-realm}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${duskio.keycloak-client}
            client-secret: eH4Keiaw0bHaFXBeNEaGIq83fAnXlsry
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${duskio.keycloak-endpoint}/realms/${duskio.keycloak-realm}

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs


duskio:
  public-endpoints: 
    - ${springdoc.api-docs.path}
    - /rapidoc.html
    - /error
  allowed-origins:
    - "*"
  keycloak-endpoint: http://localhost:8081
  keycloak-realm: duskio
  keycloak-client: duskio-api
  home-endpoint: http://localhost:8080
  