spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:file:./duskio;MODE=oracle;NON_KEYWORDS=VALUE;AUTO_SERVER=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs