spring:
  application:
    name: duskio-api
  profiles:
    active: dev

logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{MMddyyyy'T'HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%4.4t]){faint} %clr(%-25.25logger{24}){cyan}%clr(:){faint} %m%n%wEx"
